class_name NPCManager
extends Node
## NPCManager — Overhauled streaming NPC manager.
## • Spawns NPCs per-room rather than all-at-once
## • Limits total live NPCs via a configurable cap
## • Culls NPCs whose room the player has left for >30 s
## • Avoids clustering with a minimum spawn distance grid
## • Responds to museum signals when new rooms are loaded
## • Rarely spawns a CuteDemon that tells lovely facts!

const NPC_SCENE   : PackedScene  = preload("res://scenes/npc/NPC.tscn")
# Note: Can't preload CuteDemon.tscn due to script dependency - load lazily instead
# const DEMON_SCENE : PackedScene  = preload("res://scenes/npc/CuteDemon.tscn")
const WALL_MARGIN : float        = 1.2
const MIN_SPAWN_DIST : float     = 1.6   # min gap between two NPCs at spawn
const MAX_NPCS_TOTAL : int       = 30    # hard cap on simultaneous live NPCs
const NPCS_PER_ROOM_BASE : int   = 3     # baseline — scales with room area
const CULL_DELAY : float         = 30.0  # seconds before a remote room's NPCs are freed
const DEMON_SPAWN_CHANCE : float = 0.15  # 15% chance per room to spawn a cute demon

# Predefined palette — vivid but not eye-searing
const NPC_COLORS: Array[Color] = [
	Color(0.78, 0.28, 0.28),
	Color(0.28, 0.72, 0.38),
	Color(0.28, 0.35, 0.80),
	Color(0.80, 0.75, 0.22),
	Color(0.70, 0.28, 0.78),
	Color(0.22, 0.72, 0.78),
	Color(0.85, 0.48, 0.18),
	Color(0.45, 0.28, 0.72),
]

# ─────────────────────────────────────────────────────────────────────────────
# STATE
# ─────────────────────────────────────────────────────────────────────────────

var _exhibit   : Node3D = null
var _rng       : RandomNumberGenerator = RandomNumberGenerator.new()

# All live NPCs keyed by room id
var _room_npcs : Dictionary = {}   # room_id → Array[ExhibitNPC]

# Cull timers: room_id → float (time since player left)
var _cull_timers : Dictionary = {}

# Total live count
var _total_npcs : int = 0

# Player reference for proximity-based culling
var _player : Node = null

# Poll timer for checking new rooms (since TiledExhibitGenerator doesn't emit signals)
var _poll_timer : float = 0.0

# ─────────────────────────────────────────────────────────────────────────────
# INIT
# ─────────────────────────────────────────────────────────────────────────────

func init(exhibit: Node3D, count: int = -1) -> void:
	print("[NPCManager] Initializing with exhibit: %s, count: %d" % [exhibit.name if exhibit else "null", count])
	_exhibit = exhibit
	_rng.seed = hash(exhibit.get("title") if "title" in exhibit else str(randi()))
	_player   = get_tree().get_first_node_in_group("local_player")
	print("[NPCManager] Player found: %s" % ("yes" if _player else "no"))

	# Connect to RoomService signals (not Museum - it doesn't have these signals)
	var room_service = get_node_or_null("/root/RoomService")
	if room_service:
		print("[NPCManager] RoomService found, connecting signals")
		if not room_service.room_loaded.is_connected(_on_room_loaded):
			room_service.room_loaded.connect(_on_room_loaded)
	else:
		print("[NPCManager] WARNING: RoomService not found!")

	_spawn_for_all_rooms(count)


func _process(delta: float) -> void:
	_update_cull_timers(delta)
	
	# Poll for new rooms every 2 seconds (rooms are generated by TiledExhibitGenerator, not RoomService)
	_poll_timer += delta
	if _poll_timer >= 2.0:
		_poll_timer = 0.0
		_spawn_for_all_rooms(-1)


# ─────────────────────────────────────────────────────────────────────────────
# SPAWNING
# ─────────────────────────────────────────────────────────────────────────────

func _spawn_for_all_rooms(requested_count: int) -> void:
	var rooms : Array = _get_rooms()
	print("[NPCManager] Spawning NPCs: %d rooms found, total_npcs=%d/%d" % [rooms.size(), _total_npcs, MAX_NPCS_TOTAL])
	for room_data: Dictionary in rooms:
		if _total_npcs >= MAX_NPCS_TOTAL:
			break
		_spawn_in_room(room_data, -1)


func _spawn_in_room(room_data: Dictionary, count_override: int) -> void:
	var bounds     : Array   = room_data.get("bounds", [])
	if bounds.size() < 2:
		return

	var room_id : String = room_data.get("id", room_data.get("title", "room_%d" % randi()))
	if _room_npcs.has(room_id):
		return   # Already spawned for this room

	var wmin3 : Vector3 = bounds[0] if bounds[0] is Vector3 else GridUtils.grid_to_world(bounds[0])
	var wmax3 : Vector3 = bounds[1] if bounds[1] is Vector3 else GridUtils.grid_to_world(bounds[1])

	# Determine NPC count for this room (scale by area)
	var area         : float = max(1.0, (wmax3.x - wmin3.x) * (wmax3.z - wmin3.z))
	var desired      : int   = int(NPCS_PER_ROOM_BASE + area / 40.0) if count_override < 0 else count_override
	desired          = clampi(desired, 1, 8)
	desired          = min(desired, MAX_NPCS_TOTAL - _total_npcs)
	if desired <= 0:
		return

	var spawned_positions : Array[Vector3] = []
	var world_bounds       : Array = [wmin3, wmax3]
	var npcs_in_room       : Array[ExhibitNPC] = []

	print("[NPCManager] Spawning %d NPCs in room %s (area=%.1f, bounds=%s to %s)" % [desired, room_id, area, wmin3, wmax3])

	# Spawn regular NPCs with better distribution
	for _i in range(desired * 4):   # try 4× as many positions as desired
		if spawned_positions.size() >= desired:
			break
		var pos       : Vector3 = _random_pos_in_bounds(world_bounds)
		# Reject if too close to another in this batch
		var too_close : bool    = false
		for ep: Vector3 in spawned_positions:
			if ep.distance_to(pos) < MIN_SPAWN_DIST:
				too_close = true
				break
		if too_close:
			continue

		var npc : ExhibitNPC = _instantiate_npc(world_bounds)
		if not npc:
			continue
		_exhibit.add_child(npc)
		pos.y = wmin3.y + 0.1
		npc.global_position = pos  # Use global_position instead of just setting after add_child
		npc.init(pos, world_bounds)
		npc.add_to_group("npc")
		spawned_positions.append(pos)
		npcs_in_room.append(npc)
		_total_npcs += 1
		print("[NPCManager] Spawned NPC at %s, visible=%s" % [pos, npc.visible])

	if npcs_in_room.size() > 0:
		_room_npcs[room_id] = npcs_in_room

	# Rare chance to spawn a CuteDemon in this room
	if _rng.randf() < DEMON_SPAWN_CHANCE and _total_npcs < MAX_NPCS_TOTAL:
		_spawn_cute_demon(world_bounds, wmin3)


func _instantiate_npc(world_bounds: Array) -> ExhibitNPC:
	var npc : ExhibitNPC = NPC_SCENE.instantiate()
	# Body colour
	var body_mesh : MeshInstance3D = npc.get_node_or_null("BodyMesh")
	var head_mesh : MeshInstance3D = npc.get_node_or_null("HeadMesh")
	var color : Color = NPC_COLORS[_rng.randi() % NPC_COLORS.size()]
	if body_mesh:
		var mat := StandardMaterial3D.new()
		mat.albedo_color = color
		mat.roughness    = 0.65
		body_mesh.material_override = mat
		body_mesh.layers = 1  # Layer 1 (seen by camera cull mask 1048063)
		print("[NPCManager] BodyMesh material set to %s, layers=%d" % [color, body_mesh.layers])
	# Head skin tone
	if head_mesh:
		var hm := StandardMaterial3D.new()
		# Slightly randomise skin tone
		var skin : Color = Color(
			_rng.randf_range(0.80, 0.95),
			_rng.randf_range(0.65, 0.82),
			_rng.randf_range(0.50, 0.70)
		)
		hm.albedo_color = skin
		hm.roughness    = 0.45
		head_mesh.material_override = hm
		head_mesh.layers = 1  # Layer 1 (seen by camera cull mask 1048063)
		print("[NPCManager] HeadMesh material set to %s, layers=%d" % [skin, head_mesh.layers])
	return npc


func _spawn_cute_demon(world_bounds: Array, wmin3: Vector3) -> void:
	"""Spawn a CuteDemon that tells lovely facts"""
	# Lazy load the scene (can't preload due to script dependency)
	var demon_scene: PackedScene = load("res://scenes/npc/CuteDemon.tscn")
	if not demon_scene:
		return
	
	var demon: CharacterBody3D = demon_scene.instantiate()
	if not demon:
		return
	
	# Position in a visible spot
	var pos: Vector3 = _random_pos_in_bounds(world_bounds)
	pos.y = wmin3.y + 0.1
	
	_exhibit.add_child(demon)
	demon.global_position = pos
	demon.add_to_group("npc")
	_total_npcs += 1
	
	print("[NPCManager] Spawned CuteDemon in room!")


# ─────────────────────────────────────────────────────────────────────────────
# CULLING
# ─────────────────────────────────────────────────────────────────────────────

func _update_cull_timers(delta: float) -> void:
	if not is_instance_valid(_player):
		_player = get_tree().get_first_node_in_group("local_player")
		return

	var current_room : String = _player.get("current_room") if "current_room" in _player else ""

	for room_id: String in _room_npcs.keys():
		if room_id == current_room or room_id == "Lobby":
			# Player is here — reset cull timer
			_cull_timers.erase(room_id)
		else:
			_cull_timers[room_id] = _cull_timers.get(room_id, 0.0) + delta
			if _cull_timers[room_id] > CULL_DELAY:
				_cull_room(room_id)


func _cull_room(room_id: String) -> void:
	if not _room_npcs.has(room_id):
		return
	for npc: ExhibitNPC in _room_npcs[room_id]:
		if is_instance_valid(npc):
			npc.queue_free()
			_total_npcs -= 1
	_room_npcs.erase(room_id)
	_cull_timers.erase(room_id)


# ─────────────────────────────────────────────────────────────────────────────
# SIGNALS FROM MUSEUM
# ─────────────────────────────────────────────────────────────────────────────

func _on_exhibit_changed(_title: Variant = null) -> void:
	# Respawn all when a completely new exhibit is loaded
	for room_id: String in _room_npcs.keys():
		_cull_room(room_id)
	_total_npcs = 0
	call_deferred("_spawn_for_all_rooms", -1)


func _on_room_loaded(room_data: Dictionary) -> void:
	# Called when the procedural generator finishes a single room
	print("[NPCManager] room_loaded signal: %s" % room_data.get("title", "unknown"))
	if _total_npcs < MAX_NPCS_TOTAL:
		_spawn_in_room(room_data, -1)


# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

func _get_rooms() -> Array:
	if not is_instance_valid(_exhibit):
		print("[NPCManager] _get_rooms: exhibit not valid")
		return []
	if _exhibit.has_method("get_rooms_for_npcs"):
		var rooms = _exhibit.get_rooms_for_npcs()
		print("[NPCManager] _get_rooms: got %d rooms from exhibit" % rooms.size())
		return rooms
	print("[NPCManager] _get_rooms: exhibit missing get_rooms_for_npcs method")
	return []


func _random_pos_in_bounds(bounds: Array) -> Vector3:
	var bmin : Vector3 = bounds[0]
	var bmax : Vector3 = bounds[1]
	var min_x : float = bmin.x + WALL_MARGIN;  var max_x : float = bmax.x - WALL_MARGIN
	var min_z : float = bmin.z + WALL_MARGIN;  var max_z : float = bmax.z - WALL_MARGIN
	if min_x >= max_x: min_x = (bmin.x + bmax.x) * 0.5; max_x = min_x + 0.5
	if min_z >= max_z: min_z = (bmin.z + bmax.z) * 0.5; max_z = min_z + 0.5
	return Vector3(
		_rng.randf_range(min_x, max_x),
		0.0,
		_rng.randf_range(min_z, max_z)
	)


func _shuffle(arr: Array) -> void:
	for i in range(arr.size() - 1, 0, -1):
		var j : int = _rng.randi() % (i + 1)
		var tmp = arr[i];  arr[i] = arr[j];  arr[j] = tmp
